package api.data;

public class GenerateData {

	public static String getEmail() {
		String email = "autogenerated";
		String provider = "@tekschool.us";
		int randomNumber = (int) (Math.random() * 10000);
		String autoEmail = email + randomNumber + provider;
		return autoEmail;
	}

	public static String getPhoneNumber() {
		String phoneNumber = "9";
		for (int i = 0; i < 9; i++) {
			phoneNumber+= (int) (Math.random() * 10);
		}
		return phoneNumber;

	}

	public static void main(String[] args) {
		System.out.println(getPhoneNumber());
	}

}
